[app]
# if you get errors on any informationn you place inside this file
# ensure that they're placed in single quotes as apposed to double quotes

# you only need the API keys for the services you want to convert playlists from
[app.apis]
# last.fm api key used only when tracks and artists when retrieving playlist data from last.fm
lastfm_api_key = ''

[app.playlist]
# the root volume of your music service container (i.e., Navidrome)
container_root = '/music/'

# the local path to your music library, either absolute path or network path
# (e.g., \\10.0.0.2\\path\to\music or C:\path\to\music)
local_music_path = ''

# both work in the same way, where blocklist_strings is string to mever match (e.g., "(Live)")
# allowlist_strings will retain the string in track (if found) (e.g., "(English ver.)")
# seperate the strings using a comma (e.g., "(Live), (English ver.)") 
blocklist_strings = ''
allowlist_strings = ''

# default output directory for m3u8 files
default_output = ''

# below is where you should define alternative names for artists you find while using mmt
# in the case where the artist "30 Seconds To Mars" is stored locally but in the playlist
# data, it's defined as "Thirty Seconds To Mars" (you do not need to include the inverse order of names)
[app.playlist.artist_aliases]
"30 Seconds To Mars" = "Thirty Seconds To Mars"

[app.cleaner]
# location of where you download/rip your albums to
download_path = ''

[app.misc]
# versioning DO NOT CHANGE
version = '0.1.3'

